export {Auth} from './auth/Auth'
export {News} from './news/News'
export {Main} from './main/Main'
export {Profile} from './profile/Profile'
export {Header} from './header/Header'
export {Page404} from './page-404/Page404'
export {RoutesPage} from './routes-page/RoutesPage'
